Homework2
valeria-ivasheva/homework-3-4-semester pull request #3
Opened 2018-10-30 19:18 UTC by valeria-ivasheva

2018-11-03 13:45 UTC, yurii-litvinov requested changes
Почти всё правильно :)

2018-11-03 13:45 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyTask.cs
> +    public class MyTask<T> : IMyTask<T>
Имело бы смысл сделать этот класс вложенным в тредпул и приватным, чтобы пользователю не пришло в голову вызвать Get самому.

2018-11-03 13:45 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyTask.cs
> +            threadPool.AddTask(newTask);
Не, так задача-продолжение заблокирует один из потоков пула до тех пор, пока эта задача не закончится. Лучше сохранять продолжения (если эта задача ещё считается), чтобы потом сразу добавить их все, когда задача закончится.

2018-11-03 13:45 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPoolTest/MyThreadPoolTest.cs
> +            Assert.AreEqual(task.Result, 22);
Наоборот, 22, task.Result. У Assert.AreEqual первый параметр --- ожидаемое значение.

2018-11-08 18:53 UTC, yurii-litvinov requested changes
Ещё пара гонок вроде осталась, доисправляйте, пожалуйста.

2018-11-08 18:53 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +                return null;
Зачем таску тогда создавать и понапрасну беспокоить сборщик мусора? :)

2018-11-08 18:53 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +        //}
Закомментированный код не нужен

2018-11-08 18:53 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            taskQueue = null;
Ой. Прозреваю креш на строке 32 в оооочень редких случаях гонки между Shutdown и получением задачи в потоке.

2018-11-08 18:53 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +    class MyTask<T> : IMyTask<T>
private

2018-11-08 18:53 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            /// threadPool.AddTask(this);
Тоже закомментированный код, который не нужен :)

2018-11-08 18:53 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            }
А здесь может быть гонка со строкой 189. Сначала делается if (IsCompleted) тут, затем IsCompleted = true и цикл  foreach (var temp in funcsContinue) там, затем funcsContinue.Enqueue тут, и всё, продолжение никогда не исполнится.

2018-11-09 04:44 UTC, yurii-litvinov requested changes

2018-11-09 04:44 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +                    tResult = func();
Где-то тут неплохо бы func = null;, чтобы сборщик мусора мог её собрать

2018-11-09 04:44 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +                throw new ThreadPoolClosedException();
Ага, так лучше

2018-11-09 04:44 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            }
Не, один lock тут не поможет. Первый поток берёт замок и делает if (IsCompleted), его прерывают и второй поток делает IsCompleted = true в строке 181 --- ему ж замок брать не надо. И дальше по уже описанному сценарию.

2018-11-09 04:44 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/ThreadPoolClosedException.cs
> +    public class ThreadPoolClosedException : Exception
Комментарии? :)

2018-11-09 04:44 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            taskQueue = null;
Мм, это вроде не поправилось. Надо ещё один замок, видимо.

2018-11-18 18:51 UTC, yurii-litvinov requested changes

2018-11-18 18:51 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +                       closeReset.Set();
Что-то с отступом не то

2018-11-18 18:51 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            taskQueue = null;
Боюсь, это не поможет. Представим, что запускаются два потока в пуле, поток 1 и поток 2, и работает основной поток. Поток 1 доходит до строки 33 и прерывается, управление передаётся потоку 2, который тоже доходит до строки 33 и прерывается, тут в основном потоке вызывают Shutdown. Основной поток доходит до строки 94 и встаёт на closeReset.WaitOne(). Планировщик будит поток 2, тот видит, что в очереди пусто, успешно проходит threadReset.WaitOne() (его только что выставил Shutdown), делает threadReset.Set(), делает closeReset.Set() и выходит. Планировщик будит основной поток, тот проходит closeReset.WaitOne(), делает taskQueue = null и прерывается. Просыпается давно забытый поток 1, пытается взять значение из очереди и мучительно издыхает.

Я бы либо все обращения к taskQueue обернул в самый настоящий lock, либо просто не делал её null-ом (она ConcurrentQueue, поэтому спокойно относится к обращениям из нескольких потоков сразу). Может быть хорошей идеей сделать ей Clear().

2018-11-18 19:37 UTC, yurii-litvinov requested changes

2018-11-18 19:37 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            lock(locker)
Ой :) Во-первых, у очереди есть свой метод Clear, который lock-free и вообще хороший. Во-вторых, lock тут не поможет, потому что Clear вызывается только из Shutdown, который вызывается только из основного потока. В-третьих, пробела перед "(" не хватает :)

Подумайте. Цель же не сдать задачу путём внесения изменений по моим подсказкам в надежде, что рано или поздно зайдёт, а понять, как оно работает :)

2018-11-18 20:14 UTC, valeria-ivasheva commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +            lock(locker)
Проблема в примере выше с 2мя потоками была в том, что я обнуляла taskQueue и оно ломалось при проверке, но если я буду проверять на null там же, где я делаю taskQueue.TryDeque(), оно же не упадет?

2018-11-21 19:26 UTC, yurii-litvinov commented on MyThreadPool/MyThreadPool/MyThreadPool.cs
> +                        lock (taskQueue)
Ой. Так таски могут выполняться всегда только последовательно, потому что taskQueue разделяется между всеми тредами из пула, а task(); находится внутри замка.

2018-11-21 21:20 UTC, yurii-litvinov approved these changes
Да, так вроде должно работать. Зачтена.

2018-11-21 21:42 UTC, merged