Семестровая, распознаватель жестов
valeria-ivasheva/homework-3-4-semester pull request #6
Opened 2018-12-16 21:16 UTC by valeria-ivasheva

2018-12-17 09:51 UTC, yurii-litvinov requested changes

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/MainViewModel.cs
> +            string path = @"C:\Users\ACER\source\repos\RecognitionApp\RecognitionApp\IdealGestures.xml";
У меня такого нет :) Чтобы поправить, надо в свойствах файла IdealGestures.xml в проекте указать "Copy always" в "Copy to output directory"

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/RecognitionMouse.cs
> +            string path = @"C:\Users\ACER\source\repos\RecognitionApp\RecognitionApp\IdealGestures.xml";
И тут

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/DelegateCommand.cs
> +    }
Как я понимаю, это какой-то копипаст? Он оформлен не так, как всё остальное, надо бы отстайлгайдить

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/DouglasPoikerSimplification.cs
> +            List<Point> newPoint = new List<Point>();
var?

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/IdentifyCharacteristicsPoints.cs
> +                bool cond = (angle > Math.PI/9) && Distance.EuclideanDistance(lastCharPnt, points[i]) > minDist;
Пробелов не хватает :)

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/MainViewModel.cs
> +            { return thisIsGesture; }
Фигурные скобки обычно одни на строке

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/MainViewModel.cs
> +        }
Мм, `public ICommand ResetCommand => new DelegateCommand(Reset);`

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/MainViewModel.cs
> +            //var point = rec.DouglasPeucker();
Закомментированный код не нужен :)

2018-12-17 09:51 UTC, yurii-litvinov commented on RecognitionApp/RecognitionApp/RecognitionMouse.cs
> +            //{
И тут

2019-06-05 09:55 UTC, valeria-ivasheva commented
Инструмент распознавания переехал в отдельный репозиторий
https://github.com/valeria-ivasheva/recognizer

2019-06-05 09:55 UTC, closed without merging